<?php
/**
 * CharacterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CharacterApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CharacterApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getCharactersCharacterId
     *
     * Get character's public information.
     *
     */
    public function testGetCharactersCharacterId()
    {

    }

    /**
     * Test case for getCharactersCharacterIdAgentsResearch
     *
     * Get agents research.
     *
     */
    public function testGetCharactersCharacterIdAgentsResearch()
    {

    }

    /**
     * Test case for getCharactersCharacterIdChatChannels
     *
     * Get chat channels.
     *
     */
    public function testGetCharactersCharacterIdChatChannels()
    {

    }

    /**
     * Test case for getCharactersCharacterIdCorporationhistory
     *
     * Get corporation history.
     *
     */
    public function testGetCharactersCharacterIdCorporationhistory()
    {

    }

    /**
     * Test case for getCharactersCharacterIdMedals
     *
     * Get medals.
     *
     */
    public function testGetCharactersCharacterIdMedals()
    {

    }

    /**
     * Test case for getCharactersCharacterIdPortrait
     *
     * Get character portraits.
     *
     */
    public function testGetCharactersCharacterIdPortrait()
    {

    }

    /**
     * Test case for getCharactersCharacterIdStandings
     *
     * Get standings.
     *
     */
    public function testGetCharactersCharacterIdStandings()
    {

    }

    /**
     * Test case for getCharactersNames
     *
     * Get character names.
     *
     */
    public function testGetCharactersNames()
    {

    }

    /**
     * Test case for postCharactersAffiliation
     *
     * Character affiliation.
     *
     */
    public function testPostCharactersAffiliation()
    {

    }

    /**
     * Test case for postCharactersCharacterIdCspa
     *
     * Calculate a CSPA charge cost.
     *
     */
    public function testPostCharactersCharacterIdCspa()
    {

    }

}
