<?php
/**
 * CorporationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CorporationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CorporationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getCorporationsCorporationId
     *
     * Get corporation information.
     *
     */
    public function testGetCorporationsCorporationId()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdAlliancehistory
     *
     * Get alliance history.
     *
     */
    public function testGetCorporationsCorporationIdAlliancehistory()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdIcons
     *
     * Get corporation icon.
     *
     */
    public function testGetCorporationsCorporationIdIcons()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdMembers
     *
     * Get corporation members.
     *
     */
    public function testGetCorporationsCorporationIdMembers()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdRoles
     *
     * Get corporation member roles.
     *
     */
    public function testGetCorporationsCorporationIdRoles()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdStructures
     *
     * Get corporation structures.
     *
     */
    public function testGetCorporationsCorporationIdStructures()
    {

    }

    /**
     * Test case for getCorporationsNames
     *
     * Get corporation names.
     *
     */
    public function testGetCorporationsNames()
    {

    }

    /**
     * Test case for getCorporationsNpccorps
     *
     * Get npc corporations.
     *
     */
    public function testGetCorporationsNpccorps()
    {

    }

    /**
     * Test case for putCorporationsCorporationIdStructuresStructureId
     *
     * Update structure vulnerability schedule.
     *
     */
    public function testPutCorporationsCorporationIdStructuresStructureId()
    {

    }

}
