<?php
/**
 * IndustryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * IndustryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IndustryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCharactersCharacterIdIndustryJobs
     *
     * List character industry jobs.
     *
     */
    public function testGetCharactersCharacterIdIndustryJobs()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdIndustryJobs
     *
     * List corporation industry jobs.
     *
     */
    public function testGetCorporationsCorporationIdIndustryJobs()
    {
    }

    /**
     * Test case for getIndustryFacilities
     *
     * List industry facilities.
     *
     */
    public function testGetIndustryFacilities()
    {
    }

    /**
     * Test case for getIndustrySystems
     *
     * List solar system cost indices.
     *
     */
    public function testGetIndustrySystems()
    {
    }
}
