<?php
/**
 * MarketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MarketApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getMarketsGroups
     *
     * Get item groups.
     *
     */
    public function testGetMarketsGroups()
    {

    }

    /**
     * Test case for getMarketsGroupsMarketGroupId
     *
     * Get item group information.
     *
     */
    public function testGetMarketsGroupsMarketGroupId()
    {

    }

    /**
     * Test case for getMarketsPrices
     *
     * List market prices.
     *
     */
    public function testGetMarketsPrices()
    {

    }

    /**
     * Test case for getMarketsRegionIdHistory
     *
     * List historical market statistics in a region.
     *
     */
    public function testGetMarketsRegionIdHistory()
    {

    }

    /**
     * Test case for getMarketsRegionIdOrders
     *
     * List orders in a region.
     *
     */
    public function testGetMarketsRegionIdOrders()
    {

    }

    /**
     * Test case for getMarketsStructuresStructureId
     *
     * List orders in a structure.
     *
     */
    public function testGetMarketsStructuresStructureId()
    {

    }

}
