<?php
/**
 * GetAlliancesAllianceIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetAlliancesAllianceIdOkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetAlliancesAllianceIdOkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetAlliancesAllianceIdOk"
     */
    public function testGetAlliancesAllianceIdOk()
    {
    }

    /**
     * Test attribute "alliance_name"
     */
    public function testPropertyAllianceName()
    {
    }

    /**
     * Test attribute "date_founded"
     */
    public function testPropertyDateFounded()
    {
    }

    /**
     * Test attribute "executor_corp"
     */
    public function testPropertyExecutorCorp()
    {
    }

    /**
     * Test attribute "ticker"
     */
    public function testPropertyTicker()
    {
    }
}
