<?php
/**
 * GetCorporationsCorporationIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCorporationsCorporationIdOkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCorporationsCorporationIdOkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCorporationsCorporationIdOk"
     */
    public function testGetCorporationsCorporationIdOk()
    {
    }

    /**
     * Test attribute "alliance_id"
     */
    public function testPropertyAllianceId()
    {
    }

    /**
     * Test attribute "ceo_id"
     */
    public function testPropertyCeoId()
    {
    }

    /**
     * Test attribute "corporation_description"
     */
    public function testPropertyCorporationDescription()
    {
    }

    /**
     * Test attribute "corporation_name"
     */
    public function testPropertyCorporationName()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "faction"
     */
    public function testPropertyFaction()
    {
    }

    /**
     * Test attribute "member_count"
     */
    public function testPropertyMemberCount()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "ticker"
     */
    public function testPropertyTicker()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
