<?php
/**
 * GetCharactersCharacterIdWalletJournalExtraInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCharactersCharacterIdWalletJournalExtraInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Extra information for different type of transaction
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdWalletJournalExtraInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCharactersCharacterIdWalletJournalExtraInfo"
     */
    public function testGetCharactersCharacterIdWalletJournalExtraInfo()
    {
    }

    /**
     * Test attribute "alliance_id"
     */
    public function testPropertyAllianceId()
    {
    }

    /**
     * Test attribute "character_id"
     */
    public function testPropertyCharacterId()
    {
    }

    /**
     * Test attribute "contract_id"
     */
    public function testPropertyContractId()
    {
    }

    /**
     * Test attribute "corporation_id"
     */
    public function testPropertyCorporationId()
    {
    }

    /**
     * Test attribute "destroyed_ship_type_id"
     */
    public function testPropertyDestroyedShipTypeId()
    {
    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "npc_id"
     */
    public function testPropertyNpcId()
    {
    }

    /**
     * Test attribute "npc_name"
     */
    public function testPropertyNpcName()
    {
    }

    /**
     * Test attribute "planet_id"
     */
    public function testPropertyPlanetId()
    {
    }

    /**
     * Test attribute "system_id"
     */
    public function testPropertySystemId()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }
}
