<?php
/**
 * GetCorporationsCorporationIdStructures200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCorporationsCorporationIdStructures200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCorporationsCorporationIdStructures200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCorporationsCorporationIdStructures200Ok"
     */
    public function testGetCorporationsCorporationIdStructures200Ok()
    {
    }

    /**
     * Test attribute "corporation_id"
     */
    public function testPropertyCorporationId()
    {
    }

    /**
     * Test attribute "current_vul"
     */
    public function testPropertyCurrentVul()
    {
    }

    /**
     * Test attribute "fuel_expires"
     */
    public function testPropertyFuelExpires()
    {
    }

    /**
     * Test attribute "next_vul"
     */
    public function testPropertyNextVul()
    {
    }

    /**
     * Test attribute "profile_id"
     */
    public function testPropertyProfileId()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "state_timer_end"
     */
    public function testPropertyStateTimerEnd()
    {
    }

    /**
     * Test attribute "state_timer_start"
     */
    public function testPropertyStateTimerStart()
    {
    }

    /**
     * Test attribute "structure_id"
     */
    public function testPropertyStructureId()
    {
    }

    /**
     * Test attribute "system_id"
     */
    public function testPropertySystemId()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }

    /**
     * Test attribute "unanchors_at"
     */
    public function testPropertyUnanchorsAt()
    {
    }
}
